# Generated by Django 2.1.11 on 2019-08-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20190812_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='token',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
