# Generated by Django 2.1.11 on 2019-09-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_music_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
